begin;

-- remove old schema objects if they exist

drop view if exists public.student_training_progress cascade;
drop view if exists public.student_document_matrix cascade;
drop view if exists public.latest_document_submissions cascade;

drop function if exists public.sync_student_has_cv() cascade;
drop function if exists public.owns_enrollment(uuid) cascade;
drop function if exists public.current_student_profile_id() cascade;
drop function if exists public.is_admin() cascade;
drop function if exists public.set_updated_at() cascade;

drop table if exists public.document_submissions cascade;
drop table if exists public.report_types cascade;
drop table if exists public.cv_submissions cascade;
drop table if exists public.student_training_enrollments cascade;
drop table if exists public.training_cycles cascade;
drop table if exists public.admin_profiles cascade;
drop table if exists public.student_profiles cascade;
drop table if exists public.roles cascade;

drop table if exists public.forms cascade;
drop table if exists public.formtype cascade;
drop table if exists public.cvs cascade;
drop table if exists public.student cascade;
drop table if exists public.role cascade;
drop table if exists public.admin cascade;

create table public.admin (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null
);

create table public.role (
  id bigint generated by default as identity primary key,
  name text not null unique
);

insert into public.role (name)
values
  ('Software Engineer'),
  ('QA Engineer'),
  ('Business Analyst'),
  ('UI/UX Designer'),
  ('Network Engineer'),
  ('Data Scientist'),
  ('Other');

create table public.student (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text not null,
  index_number text not null unique,
  contact_number text,
  linkedin_url text,
  github_url text,
  ishascv boolean not null default false
);

create table public.cv (
  id bigint generated by default as identity primary key,
  studentid bigint not null unique references public.student(id) on delete cascade,
  url text not null,
  roleid bigint not null references public.role(id) on delete restrict
);

create table public.formtype (
  id bigint generated by default as identity primary key,
  name text not null unique
);

insert into public.formtype (name)
values
  ('Form A'),
  ('Form B'),
  ('Form C1'),
  ('Form C2'),
  ('Form C3'),
  ('Form C4'),
  ('Form D'),
  ('Form E'),
  ('Weekly Journal'),
  ('Final Presentation'),
  ('Final Report');

create table public.form (
  id bigint generated by default as identity primary key,
  studentid bigint not null references public.student(id) on delete cascade,
  formtypeid bigint not null references public.formtype(id) on delete restrict,
  data jsonb not null default '{}'::jsonb,
  url text
);

commit;
